import Head from 'next/head'
import { useContext } from "react";
import { GlobalContext } from "@utils/GlobalContext";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import Link from 'next/link';
import { useRouter } from 'next/router'

export async function getServerSideProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['second'])),
      // Will be passed to the page component as props
    },
  };
}

export default function Second() {
  const router = useRouter()
  const { t } = useTranslation('second');
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 h-screen flex items-center justify-center flex-wrap">
        <div className="max-w-xl text-center">
          <h1 className="text-4xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-3">
            {t('h1')}
          </h1>
          <p className="text-base text-neutral-600 dark:text-gray-200 mb-4">
            {t('p')}
          </p>

          <Link href='/second' locale={router.locale === 'en' ? 'id' : 'en'}>
            <button className="bg-blue-600 mx-2 text-white px-4 py-1 rounded mb-4 shadow-md font-medium hover:bg-blue-800 transition-all">
              {t('change-locale')}
            </button>
          </Link>
          <Link href='/'>
            <button className="text-blue-600 mx-2 px-4 py-1 font-medium hover:text-blue-500 transition-all">
              {t('back-to-home')}
            </button>
          </Link>

          <div className="flex justify-center">
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
